In [1]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

## Extracting features of 2020 movies from Wikipedia

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [3]:
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [4]:
tables = soup.find_all('table',class_='wikitable sortable')

In [5]:
len(tables)

4

In [6]:
type(tables[0])

bs4.element.Tag

In [7]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

In [8]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [9]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2]
1,JANUARY,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3]
2,JANUARY,10,Like a Boss,Paramount Pictures,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4]
3,JANUARY,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN
4,JANUARY,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5]
...,...,...,...,...,...,...
264,DECEMBER,25,We Can Be Heroes,Netflix / Troublemaker Studios,Robert Rodriguez (director/screenplay); Priyan...,[237]
265,DECEMBER,25,News of the World,Universal Pictures / Perfect World Pictures,Paul Greengrass (director/screenplay); Luke Da...,[238]
266,DECEMBER,25,One Night in Miami...,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,[239]
267,DECEMBER,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,[240]
268,DECEMBER,30,Pieces of a Woman,Netflix / Bron Studios,Kornél Mundruczó (director); Kata Wéber (scree...,[241]

In [10]:
df_2020 = df[['Title','Cast and crew']]

In [11]:
df_2020

                     Title                                      Cast and crew
0               The Grudge  Nicolas Pesce (director/screenplay); Andrea Ri...
1               Underwater  William Eubank (director); Brian Duffield, Ada...
2              Like a Boss  Miguel Arteta (director); Sam Pitman, Adam Col...
3            Three Christs  Jon Avnet (director/screenplay); Eric Nazarian...
4        Inherit the Viper  Anthony Jerjen (director); Andrew Crabtree (sc...
..                     ...                                                ...
264       We Can Be Heroes  Robert Rodriguez (director/screenplay); Priyan...
265      News of the World  Paul Greengrass (director/screenplay); Luke Da...
266  One Night in Miami...  Regina King (director); Kemp Powers (screenpla...
267  Promising Young Woman  Emerald Fennell (director/screenplay); Carey M...
268      Pieces of a Woman  Kornél Mundruczó (director); Kata Wéber (scree...

[269 rows x 2 columns]

In [12]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in d:\users\mani\anaconda3\lib\site-packages (1.7.1)
Requirement already satisfied: requests in d:\users\mani\anaconda3\lib\site-packages (from tmdbv3api) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\mani\anaconda3\lib\site-packages (from requests->tmdbv3api) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\users\mani\anaconda3\lib\site-packages (from requests->tmdbv3api) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in d:\users\mani\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\users\mani\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.24.2)

In [13]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '5492165c61b1a21c06eb3a3b578a6339'

In [14]:
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [15]:
df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
df_2020

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery Thriller
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama Thriller Crime
...,...,...,...
264,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Action Fantasy Family Drama Comedy
265,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Action Adventure Drama Western
266,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama
267,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama
268,Pieces of a Woman,Kornél Mundruczó (director); Kata Wéber (scree...,Drama

In [17]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [18]:
df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [19]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [20]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [21]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [22]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [23]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [24]:
df_2020['actor_3_name'] = df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [25]:
df_2020

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery Thriller,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama Thriller Crime,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs
...,...,...,...,...,...,...,...
264,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Action Fantasy Family Drama Comedy,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin
265,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Action Adventure Drama Western,Paul Greengrass,Tom Hanks,Helena Zengel,NaN
266,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge
267,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie
268,Pieces of a Woman,Kornél Mundruczó (director); Kata Wéber (scree...,Drama,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker

In [26]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [27]:
new_df20 = df_2020.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [28]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho,Horror Mystery Thriller,The Grudge
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,Underwater
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama Thriller Crime,Inherit the Viper
...,...,...,...,...,...,...
264,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Drama Comedy,We Can Be Heroes
265,Paul Greengrass,Tom Hanks,Helena Zengel,NaN,Action Adventure Drama Western,News of the World
266,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami...
267,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,Promising Young Woman
268,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,Pieces of a Woman

In [29]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [30]:
new_df20.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      3
actor_3_name     26
genres            0
movie_title       0
comb             26
dtype: int64

In [31]:
new_df20 = new_df20.dropna(how='any')

In [32]:
new_df20.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [33]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [34]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho,Horror Mystery Thriller,the grudge,Andrea Riseborough Demián Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,three christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama Thriller Crime,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
263,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Family Animation Comedy Drama Music Fantasy,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
264,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Drama Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
266,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
267,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
268,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

In [35]:
old_df = pd.read_csv('datasets/final_data.csv')

In [36]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5867,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
5868,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5869,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama Action Thriller,1917,George MacKay Dean-Charles Chapman Mark Strong...
5870,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5871,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [37]:
old_df = old_df.append(new_df20,ignore_index=True)

In [38]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6110,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Family Animation Comedy Drama Music Fantasy,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
6111,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Drama Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
6112,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
6113,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
6114,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

## Extracting features of 2021 movies from Wikipedia

In [39]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"

In [40]:
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [41]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

D:\Users\mani\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [42]:
df

,Cast and crew,Opening,Opening.1,Production company,Ref,Ref.,Title,Unnamed: 0,"Wikimedia Commons has media related to Films of the United States, 2021."
0,Ricky Staub (director/screenplay); Dan Walser ...,APRIL,2.0,Netflix,NaN,[50],Concrete Cowboy,NaN,NaN
1,Evan Spiliotopoulos (director/screenplay); Jef...,APRIL,2.0,Screen Gems / Ghost House Pictures,NaN,[51],The Unholy,NaN,NaN
2,Vaughn Stein (director); David Murray (screenp...,APRIL,2.0,Vertical Entertainment,NaN,[52],Every Breath You Take,NaN,NaN
3,Emma Seligman (director/screenplay); Rachel Se...,APRIL,2.0,Utopia,NaN,NaN,Shiva Baby,NaN,NaN
4,Neil Burger (director/screenplay); Tye Sherida...,APRIL,9.0,Lionsgate / Thunder Road Films,NaN,NaN,Voyagers,NaN,NaN
...,...,...,...,...,...,...,...,...,...
80,"Erwin brothers (directors); David Aaron, Jon E...",DECEMBER,10.0,Lionsgate,NaN,[108],American Underdog: The Kurt Warner Story,NaN,NaN
81,"Jon Watts (director); Chris McKenna, Erik Somm...",DECEMBER,17.0,Columbia Pictures / Marvel Studios,NaN,[109],Spider-Man: No Way Home,NaN,NaN
82,Lana Wachowski (director/screenplay); Aleksand...,DECEMBER,22.0,HBO Max / Warner Bros. Pictures / Village Road...,NaN,[110],Untitled fourth Matrix film,NaN,NaN
83,Garth Jennings (director/screenplay); Matthew ...,DECEMBER,22.0,Universal Pictures / Illumination,NaN,[111],Sing 2,NaN,NaN
84,NaN,DECEMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_2021 = df[['Title','Cast and crew']]

In [44]:
df_2021

,Title,Cast and crew
0,Concrete Cowboy,Ricky Staub (director/screenplay); Dan Walser ...
1,The Unholy,Evan Spiliotopoulos (director/screenplay); Jef...
2,Every Breath You Take,Vaughn Stein (director); David Murray (screenp...
3,Shiva Baby,Emma Seligman (director/screenplay); Rachel Se...
4,Voyagers,Neil Burger (director/screenplay); Tye Sherida...
...,...,...
80,American Underdog: The Kurt Warner Story,"Erwin brothers (directors); David Aaron, Jon E..."
81,Spider-Man: No Way Home,"Jon Watts (director); Chris McKenna, Erik Somm..."
82,Untitled fourth Matrix film,Lana Wachowski (director/screenplay); Aleksand...
83,Sing 2,Garth Jennings (director/screenplay); Matthew ...
84,NaN,NaN

In [45]:
df_2021['genres'] = df_2021['Title'].map(lambda x: get_genre(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [46]:
df_2021

,Title,Cast and crew,genres
0,Concrete Cowboy,Ricky Staub (director/screenplay); Dan Walser ...,Drama Western
1,The Unholy,Evan Spiliotopoulos (director/screenplay); Jef...,Horror
2,Every Breath You Take,Vaughn Stein (director); David Murray (screenp...,Thriller
3,Shiva Baby,Emma Seligman (director/screenplay); Rachel Se...,Comedy Drama
4,Voyagers,Neil Burger (director/screenplay); Tye Sherida...,Science Fiction Thriller
...,...,...,...
80,American Underdog: The Kurt Warner Story,"Erwin brothers (directors); David Aaron, Jon E...",Drama
81,Spider-Man: No Way Home,"Jon Watts (director); Chris McKenna, Erik Somm...",Action Adventure Science Fiction Fantasy
82,Untitled fourth Matrix film,Lana Wachowski (director/screenplay); Aleksand...,NaN
83,Sing 2,Garth Jennings (director/screenplay); Matthew ...,Music Animation Comedy Family
84,NaN,NaN,NaN

In [47]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [48]:
df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [49]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [50]:
df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [52]:
df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [53]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [54]:
df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3(str(x)))

D:\Users\mani\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [55]:
df_2021

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Concrete Cowboy,Ricky Staub (director/screenplay); Dan Walser ...,Drama Western,Ricky Staub,Idris Elba,Caleb McLaughlin,Jharrel Jerome
1,The Unholy,Evan Spiliotopoulos (director/screenplay); Jef...,Horror,Evan Spiliotopoulos,Jeffrey Dean Morgan,Katie Aselton,William Sadler
2,Every Breath You Take,Vaughn Stein (director); David Murray (screenp...,Thriller,Vaughn Stein,Casey Affleck,Sam Claflin,Veronica Ferres
3,Shiva Baby,Emma Seligman (director/screenplay); Rachel Se...,Comedy Drama,Emma Seligman,Rachel Sennot,Molly Gordon,Polly Draper
4,Voyagers,Neil Burger (director/screenplay); Tye Sherida...,Science Fiction Thriller,Neil Burger,Tye Sheridan,Lily-Rose Depp,Fionn Whitehead
...,...,...,...,...,...,...,...
80,American Underdog: The Kurt Warner Story,"Erwin brothers (directors); David Aaron, Jon E...",Drama,Erwin brothers,Zachary Levi,Anna Paquin,Ser'Darius Blain
81,Spider-Man: No Way Home,"Jon Watts (director); Chris McKenna, Erik Somm...",Action Adventure Science Fiction Fantasy,Jon Watts,Tom Holland,Zendaya,Jacob Batalon
82,Untitled fourth Matrix film,Lana Wachowski (director/screenplay); Aleksand...,NaN,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II
83,Sing 2,Garth Jennings (director/screenplay); Matthew ...,Music Animation Comedy Family,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson
84,NaN,NaN,NaN,nan,nan,NaN,NaN

In [56]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [57]:
new_df21 = df_2021.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [58]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Ricky Staub,Idris Elba,Caleb McLaughlin,Jharrel Jerome,Drama Western,Concrete Cowboy
1,Evan Spiliotopoulos,Jeffrey Dean Morgan,Katie Aselton,William Sadler,Horror,The Unholy
2,Vaughn Stein,Casey Affleck,Sam Claflin,Veronica Ferres,Thriller,Every Breath You Take
3,Emma Seligman,Rachel Sennot,Molly Gordon,Polly Draper,Comedy Drama,Shiva Baby
4,Neil Burger,Tye Sheridan,Lily-Rose Depp,Fionn Whitehead,Science Fiction Thriller,Voyagers
...,...,...,...,...,...,...
80,Erwin brothers,Zachary Levi,Anna Paquin,Ser'Darius Blain,Drama,American Underdog: The Kurt Warner Story
81,Jon Watts,Tom Holland,Zendaya,Jacob Batalon,Action Adventure Science Fiction Fantasy,Spider-Man: No Way Home
82,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,NaN,Untitled fourth Matrix film
83,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Music Animation Comedy Family,Sing 2
84,nan,nan,NaN,NaN,NaN,NaN

In [59]:
new_df21['director_name'] = new_df21['director_name'].replace(np.nan, 'unknown')
new_df21['actor_1_name'] = new_df21['actor_1_name'].replace(np.nan, 'unknown')
new_df21['actor_2_name'] = new_df21['actor_2_name'].replace(np.nan, 'unknown')
new_df21['actor_3_name'] = new_df21['actor_3_name'].replace(np.nan, 'unknown')
new_df21['genres'] = new_df21['genres'].replace(np.nan, 'unknown')
new_df21['movie_title'] = new_df21['movie_title'].replace(np.nan, 'unknown')

In [60]:
new_df21['comb'] = new_df21['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' '+ new_df21['actor_3_name'] + ' '+ new_df21['director_name'] +' ' + new_df21['genres']

In [61]:
new_df21.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [62]:
new_df21 = new_df21.dropna(how='any')

In [63]:
new_df21.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [64]:
new_df21['movie_title'] = new_df21['movie_title'].str.lower()

In [65]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Ricky Staub,Idris Elba,Caleb McLaughlin,Jharrel Jerome,Drama Western,concrete cowboy,Idris Elba Caleb McLaughlin Jharrel Jerome Ric...
1,Evan Spiliotopoulos,Jeffrey Dean Morgan,Katie Aselton,William Sadler,Horror,the unholy,Jeffrey Dean Morgan Katie Aselton William Sadl...
2,Vaughn Stein,Casey Affleck,Sam Claflin,Veronica Ferres,Thriller,every breath you take,Casey Affleck Sam Claflin Veronica Ferres Vaug...
3,Emma Seligman,Rachel Sennot,Molly Gordon,Polly Draper,Comedy Drama,shiva baby,Rachel Sennot Molly Gordon Polly Draper Emma S...
4,Neil Burger,Tye Sheridan,Lily-Rose Depp,Fionn Whitehead,Science Fiction Thriller,voyagers,Tye Sheridan Lily-Rose Depp Fionn Whitehead Ne...
...,...,...,...,...,...,...,...
80,Erwin brothers,Zachary Levi,Anna Paquin,Ser'Darius Blain,Drama,american underdog: the kurt warner story,Zachary Levi Anna Paquin Ser'Darius Blain Erwi...
81,Jon Watts,Tom Holland,Zendaya,Jacob Batalon,Action Adventure Science Fiction Fantasy,spider-man: no way home,Tom Holland Zendaya Jacob Batalon Jon Watts Ac...
82,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,unknown,untitled fourth matrix film,Keanu Reeves Carrie-Anne Moss Yahya Abdul-Mate...
83,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Music Animation Comedy Family,sing 2,Matthew McConaughey Reese Witherspoon Scarlett...
84,nan,nan,unknown,unknown,unknown,unknown,nan unknown unknown nan unknown

In [66]:
final_df = old_df.append(new_df21,ignore_index=True)

In [67]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6195,Erwin brothers,Zachary Levi,Anna Paquin,Ser'Darius Blain,Drama,american underdog: the kurt warner story,Zachary Levi Anna Paquin Ser'Darius Blain Erwi...
6196,Jon Watts,Tom Holland,Zendaya,Jacob Batalon,Action Adventure Science Fiction Fantasy,spider-man: no way home,Tom Holland Zendaya Jacob Batalon Jon Watts Ac...
6197,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,unknown,untitled fourth matrix film,Keanu Reeves Carrie-Anne Moss Yahya Abdul-Mate...
6198,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Music Animation Comedy Family,sing 2,Matthew McConaughey Reese Witherspoon Scarlett...
6199,nan,nan,unknown,unknown,unknown,unknown,nan unknown unknown nan unknown

In [68]:
final_df.to_csv('main_data.csv',index=False)